version: '2'

services:
  fpm:
    image: 'akeneo/fpm:php-7.1'
    user: 'docker'
    volumes:
      - './:/srv/pim'
    working_dir: '/srv/pim'
  node:
    image: 'juliensnz/node'
    user: 'node'
    volumes:
      - './:/srv/pim'
    working_dir: '/srv/pim'

  httpd:
    image: 'httpd:2.4'
    depends_on:
      - 'fpm'
    ports:
      - '${DOCKER_PORT_HTTP}:80'
    volumes:
      - './:/srv/pim:ro'
      - './docker/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro'
      - './docker/akeneo.conf:/usr/local/apache2/conf/vhost.conf:ro'

  mysql:
    image: 'mysql:5.7'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'akeneo_pim'
      MYSQL_PASSWORD: 'akeneo_pim'
      MYSQL_DATABASE: 'akeneo_pim'

  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:5.5.3'
    environment:
      ES_JAVA_OPTS: '-Xms512m -Xmx512m'
      discovery.type: 'single-node'
